#!/usr/bin/env bash
# Move the demo app between the states the asset scenarios need.
#
# Vite's hot reload picks every change up instantly, so a capture taken right
# after the command lands on the new state — which is what makes the frames
# deterministic enough to stitch with ffmpeg.
#
#   ./step.sh 0                 pricing: all three defects present
#   ./step.sh 1                 pricing: heading fixed
#   ./step.sh 2                 pricing: heading + price baseline fixed
#   ./step.sh 3                 pricing: all fixed (the "after" state)
#   ./step.sh checkout-broken   checkout: totals render as NaN
#   ./step.sh checkout-fixed    checkout: totals render correctly
#   ./step.sh reset             back to the shipped state (0 + checkout-broken)
#   ./step.sh status            what state the app is in right now

set -euo pipefail

cd "$(dirname "$0")"

SRC="src"
OVERRIDES="$SRC/overrides.css"
MAIN="$SRC/main.js"

BROKEN_LINE='  const reduction = subtotal * discount; // NaN'
FIXED_LINE='  const reduction = subtotal * (Number.parseFloat(discount) / 100);'

write_overrides() {
  local upto="$1"
  {
    echo "/* Generated by ./step.sh — do not edit by hand."
    if [[ "$upto" -eq 0 ]]; then
      echo "   Currently at step 0: no fixes applied. */"
    else
      echo "   Currently at step $upto. */"
    fi
    for ((i = 1; i <= upto; i++)); do
      echo
      cat "$SRC/steps/fix-$i.css"
    done
  } > "$OVERRIDES"
  echo "pricing → step $upto"
}

set_checkout() {
  local want="$1"
  if [[ "$want" == "fixed" ]]; then
    if grep -qF "$FIXED_LINE" "$MAIN"; then
      echo "checkout → already fixed"
      return
    fi
    grep -qF "$BROKEN_LINE" "$MAIN" || {
      echo "error: expected line not found in $MAIN — has it been edited?" >&2
      exit 1
    }
    # A literal replacement, so the CSS-free parts of main.js stay untouched.
    python3 - "$MAIN" "$BROKEN_LINE" "$FIXED_LINE" <<'PY'
import sys
path, old, new = sys.argv[1], sys.argv[2], sys.argv[3]
text = open(path).read()
open(path, 'w').write(text.replace(old, new, 1))
PY
    echo "checkout → fixed"
  else
    if grep -qF "$BROKEN_LINE" "$MAIN"; then
      echo "checkout → already broken"
      return
    fi
    python3 - "$MAIN" "$FIXED_LINE" "$BROKEN_LINE" <<'PY'
import sys
path, old, new = sys.argv[1], sys.argv[2], sys.argv[3]
text = open(path).read()
open(path, 'w').write(text.replace(old, new, 1))
PY
    echo "checkout → broken"
  fi
}

status() {
  local step
  step=$(sed -n 's|.*Currently at step \([0-9]\).*|\1|p' "$OVERRIDES" | head -1)
  echo "pricing:  step ${step:-unknown}"
  if grep -qF "$FIXED_LINE" "$MAIN"; then
    echo "checkout: fixed"
  else
    echo "checkout: broken"
  fi
}

case "${1:-}" in
  0 | 1 | 2 | 3) write_overrides "$1" ;;
  checkout-fixed) set_checkout fixed ;;
  checkout-broken) set_checkout broken ;;
  reset)
    write_overrides 0
    set_checkout broken
    ;;
  status) status ;;
  *)
    sed -n '2,15p' "$0" | sed 's|^# \{0,1\}||'
    exit 1
    ;;
esac
